// <auto-generated />
using System;
using MTG_MVC_OMG.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MTG_MVC_OMG.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210102223236_justInCase")]
    partial class justInCase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("MTG_MVC_OMG.Models.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Colors");
                });

            modelBuilder.Entity("MTG_MVC_OMG.Models.Format", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Formats");
                });

            modelBuilder.Entity("MTG_MVC_OMG.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("ColorId")
                        .HasColumnType("int");

                    b.Property<int?>("FormatId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PreferredColor")
                        .HasColumnType("int");

                    b.Property<int>("PreferredFormat")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ColorId");

                    b.HasIndex("FormatId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("MTG_MVC_OMG.Models.Player", b =>
                {
                    b.HasOne("MTG_MVC_OMG.Models.Color", null)
                        .WithMany("Players")
                        .HasForeignKey("ColorId");

                    b.HasOne("MTG_MVC_OMG.Models.Format", null)
                        .WithMany("Players")
                        .HasForeignKey("FormatId");
                });

            modelBuilder.Entity("MTG_MVC_OMG.Models.Color", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("MTG_MVC_OMG.Models.Format", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
